# Generated by Django 3.1.7 on 2021-03-01 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210301_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='p',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_product_order_item', to='app.noncustomproduct'),
        ),
    ]
